### ISSUE TITLE
práctica 2 Interfaz gráfica en Visual Studio

### ISSUE THREAD

**Issue by OFELHER93** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-topicosadobexd-MJO#2]

**Comment by Elisahadad** [comment]
[](url)
[Practica 2 Interfaz Grafica.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-topicosadobexd-MJO/files/8085195/Practica.2.Interfaz.Grafica.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion...

**Comment by Yareli-Perez** [comment]
calificación = 85

**Comment by josealfredo79** [comment]
La calificacion debe aplicarse con una regla de 3 sobre el maximo que es 20%
